config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts
  
   root "posts#index"

get '/:name' => 'posts#user_posts', as: :user_posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
   private

    def sign_up_params
        devise_parameter_sanitizer.sanitize(:sign_up)
    end

    def account_update_params
        devise_parameter_sanitizer.sanitize(:account_update)
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :user
    belongs_to :post
    
end

app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user
    has_many :comments
    
    paginates_per 3
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         mount_uploader :avatar, AvatarUploader
         
         has_many :posts
         has_many :comments
         
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :avatar, :email, :password) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :avatar, :email, :password, :current_password) }
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id, :user_name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    
    @comment = Comment.new
    
  end
  
  def user_posts
    
    @user = User.find_by(username: params[:name])
  
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry, :user_id, :user_name)
    end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
    
    @name = params[:name]
    
  end

  def about
    
    @color = params[:color]
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.label :comment_entry %>
    <%= form.text_area :comment_entry, placeholder: "Comment here", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :post_id, value: @post.id %>
  </div>
  

  <div class="actions">
    <%= form.submit "Create Comment", class: "btn btn-success" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="style.css" rel="stylesheet">
    
  </head>

  <body id="moon">
    <nav class="navbar navbar-expand-sm navbar-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/posts">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul>
          <li class="nav-item">
            <% if user_signed_in? %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-sm btn-info" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-danger" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <div class=container>
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="row center-content-md-center">
    <div class="col">
      <div class="col-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder: "Blog Title", class: "form-control" %>
      </div>

      <div class="form-group">
        
        <%= form.hidden_field :user_id, value: current_user.id %>
      </div>

      <div class="form-group">
        <%= form.label :blog_entry %>
        <%= form.text_area :blog_entry, placeholder: "Tell the story...", class: "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

Welcome <%= current_user.username %>
<%= image_tag(current_user.avatar.url, :class => "custom") %>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Blog entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to post.user.username, user_posts_path(name: post.user.username) %></td>
        <td><%= post.blog_entry.html_safe %></td>
        <td class="btn btn-sm btn-primary"><%= link_to 'Show', post %></td>
        <td class="btn btn-sm btn-success"><%= link_to 'Edit', edit_post_path(post) %></td>
        <td class="btn btn-sm btn-danger"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @posts %><br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.user.username %>
</p>

<p>
  <strong>Blog entry:</strong>
  <%= @post.blog_entry.html_safe %>
</p>

<div id="comments">
  <%= render 'comments/form', comment: @comment %>
  
    <% @post.comments.each do |comment| %>
  
    <p>
      <%= comment.author %> said...<br/>
      <%= comment.comment_entry %>
    </p>
  
  <% end %>
  

</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/user_posts.html.erb
<h1>All posts by <% @user.username %></h1>


<% @user.posts.each do |post| %>

    <div class="row" id="black-cat">
        <div class="col-md-8 col-md-offset-s">
            <div class="well">
                <h3><%= post.title %></h3>
                <p><em>posted on <% post.created_at %></em></p>
                
                <p>
                    <%= post.blog_entry.html_safe %>
                </p>
                
                <p>
                    <%= link_to 'show', post, class: "btn btn-info" %>
                    <% if current_user.id == post.user.id %>
                        <%= link_to 'edit', edit_post_path(post), class: "btn btn-success" %>
                        <%= link_to 'destroy', post, method: :delete, data: {confirm: 'Are you sure??'}, class: "btn btn-danger" %>
                    <% end %>
                </p>
                
            </div>
        </div>
    </div>
<% end %>

app/views/practice/about.html.erb
<style>
    
    #first_color{
        background-color: <%= @color %>;
        color: white;
        width: 300px;
        height: 300px;
    }
    
    
</style>

<div id="first_color">
    
    <p>
        <%= @color.upcase %> This is the color you selected!
    </p>
    
</div>

<div>
    
    <%= form_tag index_path do %>
        
        <p><%= text_field_tag :name, nil, placeholder: "What's your name?" %></p>
        <p><%= submit_tag :BOOM! %></p>
    
    <% end %>
    
</div>

app/views/practice/index.html.erb
<h1>Please select the background color you'd like to populate moving forward:</h1>

<% if !@name.blank? %>
    <h2>Welcome back, <%= @name %></h2>
<% end %>

<p>
    <%= link_to "Red", about_path(color: "maroon") %>
</p>

<p>
    <%= link_to "Blue", about_path(color: "aqua") %>
</p>

<p>
    <%= link_to "Green", about_path(color: "lime") %>
</p>


<p>
    <%= link_to "Purple", about_path(color: "#ff0066") %>
</p>